export type Profile = {
  id: number;
  name: string;
  age: number;
  location: string;
  tribe: string;
  distance: string;
  verified: boolean;
  online: boolean;
  joined: string;
  interests: string[];
  bio: string;
  image: string;
  occupation: string;
  education: string;
  religion: string;
  height: string;
  languages: string[];
  lifestyle: string;
  lookingFor: string;
  compatibility: number;
};

export const profiles: Profile[] = [
  {
    id: 1,
    name: "Amaka",
    age: 25,
    location: "Lagos",
    tribe: "Igbo",
    distance: "3 km away",
    verified: true,
    online: true,
    joined: "Joined recently",
    interests: ["Business", "Travel", "Music"],
    bio: "Confident, ambitious, and drawn to meaningful conversations and genuine connections.",
    image: "/profiles/amaka.jpg",
    occupation: "Brand Strategist",
    education: "University of Lagos",
    religion: "Christian",
    height: "168 cm",
    languages: ["English", "Igbo"],
    lifestyle: "Social, active, non-smoker",
    lookingFor: "A serious relationship",
    compatibility: 94,
  },
  {
    id: 2,
    name: "Aisha",
    age: 26,
    location: "Abuja",
    tribe: "Hausa",
    distance: "7 km away",
    verified: true,
    online: true,
    joined: "Active today",
    interests: ["Family", "Lifestyle", "Food"],
    bio: "Calm, focused, family-oriented, and interested in building something intentional.",
    image: "/profiles/aisha.jpg",
    occupation: "Pharmacist",
    education: "University of Abuja",
    religion: "Muslim",
    height: "165 cm",
    languages: ["English", "Hausa"],
    lifestyle: "Modest, health-conscious",
    lookingFor: "Marriage-minded connection",
    compatibility: 91,
  },
  {
    id: 3,
    name: "Temi",
    age: 24,
    location: "Ibadan",
    tribe: "Yoruba",
    distance: "5 km away",
    verified: true,
    online: false,
    joined: "Active 20m ago",
    interests: ["Fashion", "Faith", "Movies"],
    bio: "Fun, respectful, creative, and always ready for good conversation and positive energy.",
    image: "/profiles/temi.jpg",
    occupation: "Fashion Designer",
    education: "University of Ibadan",
    religion: "Christian",
    height: "170 cm",
    languages: ["English", "Yoruba"],
    lifestyle: "Creative, outgoing",
    lookingFor: "Dating with intention",
    compatibility: 89,
  },
  {
    id: 4,
    name: "Kemi",
    age: 28,
    location: "Lekki",
    tribe: "Yoruba",
    distance: "2 km away",
    verified: true,
    online: true,
    joined: "Joined this week",
    interests: ["Luxury", "Travel", "Fitness"],
    bio: "Elegant lifestyle, ambitious mindset, and a soft spot for travel and new experiences.",
    image: "/profiles/kemi.jpg",
    occupation: "Real Estate Consultant",
    education: "Babcock University",
    religion: "Christian",
    height: "172 cm",
    languages: ["English", "Yoruba"],
    lifestyle: "Fitness-focused, social",
    lookingFor: "A confident life partner",
    compatibility: 96,
  },
  {
    id: 5,
    name: "Ada",
    age: 27,
    location: "Port Harcourt",
    tribe: "Igbo",
    distance: "9 km away",
    verified: true,
    online: false,
    joined: "Active 1h ago",
    interests: ["Business", "Networking", "Books"],
    bio: "Driven, thoughtful, and focused on creating a beautiful life with the right person.",
    image: "/profiles/ada.jpg",
    occupation: "Financial Analyst",
    education: "University of Port Harcourt",
    religion: "Christian",
    height: "166 cm",
    languages: ["English", "Igbo"],
    lifestyle: "Career-focused, calm",
    lookingFor: "Long-term relationship",
    compatibility: 88,
  },
  {
    id: 6,
    name: "Ifeoma",
    age: 29,
    location: "Enugu",
    tribe: "Igbo",
    distance: "6 km away",
    verified: true,
    online: true,
    joined: "Active now",
    interests: ["Culture", "Wellness", "Reading"],
    bio: "Mature, respectful, intentional, and happiest around honest people with warm hearts.",
    image: "/profiles/ifeoma.jpg",
    occupation: "Medical Doctor",
    education: "University of Nigeria",
    religion: "Christian",
    height: "169 cm",
    languages: ["English", "Igbo"],
    lifestyle: "Balanced, wellness-minded",
    lookingFor: "A committed relationship",
    compatibility: 93,
  },
  {
    id: 7,
    name: "Zainab",
    age: 24,
    location: "Kano",
    tribe: "Hausa",
    distance: "4 km away",
    verified: true,
    online: false,
    joined: "Active today",
    interests: ["Family", "Culture", "Cooking"],
    bio: "Kind-hearted, grounded, and values respect, family, laughter, and genuine companionship.",
    image: "/profiles/zainab.jpg",
    occupation: "Architect",
    education: "Bayero University Kano",
    religion: "Muslim",
    height: "164 cm",
    languages: ["English", "Hausa"],
    lifestyle: "Modest, family-oriented",
    lookingFor: "A respectful partner",
    compatibility: 87,
  },
  {
    id: 8,
    name: "Chidinma",
    age: 26,
    location: "Owerri",
    tribe: "Igbo",
    distance: "8 km away",
    verified: true,
    online: true,
    joined: "Joined recently",
    interests: ["Travel", "Dance", "Lifestyle"],
    bio: "Positive energy, adventurous spirit, and always ready to enjoy the best parts of life.",
    image: "/profiles/chidinma.jpg",
    occupation: "Content Creator",
    education: "Imo State University",
    religion: "Christian",
    height: "167 cm",
    languages: ["English", "Igbo"],
    lifestyle: "Active, adventurous",
    lookingFor: "Chemistry and commitment",
    compatibility: 90,
  },
];

export const notifications = [
  { id: 1, title: "New profile view", text: "Someone nearby viewed your profile.", time: "2m" },
  { id: 2, title: "You have a new like", text: "Upgrade to see who liked you.", time: "18m" },
  { id: 3, title: "Top Pick refreshed", text: "Your daily Top Picks are ready.", time: "1h" },
];
